In [1]:
import torch

In [2]:
x = torch.empty(5,3) #创建张量
print(x)

tensor([[ 4.1877e-38, -2.1524e-10, -2.1876e+02],
        [ 4.1877e-38, -2.1524e-10, -8.7507e+02],
        [ 4.1877e-38, -2.1525e-10, -3.5003e+03],
        [ 4.1877e-38, -2.1525e-10, -1.8083e-22],
        [ 4.1877e-38, -2.1525e-10, -1.4002e+04]])


In [4]:
x = torch.rand(5,3) #随机张量
print(x)

tensor([[0.3821, 0.8112, 0.7124],
        [0.8856, 0.5740, 0.9300],
        [0.4547, 0.1474, 0.9945],
        [0.5063, 0.3456, 0.6025],
        [0.1465, 0.7926, 0.4192]])


In [10]:
x = torch.zeros(5,3,dtype = torch.long) #创建全为0的张量,数据类型为long
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [14]:
x = torch.tensor([5.5,3]) #根据数据创建
print(x)
x = x.new_ones(5,3,dtype = torch.float64)
print(x)
x = torch.randn_like(x,dtype=torch.float) #指定新的数据类型，randn：标准分布，rand:均匀分布，normal(mean,std)：正态分布
print(x)
print(x.size())
print(x.shape) #返回tuple类型

tensor([5.5000, 3.0000])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.3776,  0.0080,  1.3954],
        [ 0.5815, -0.2561,  2.3722],
        [ 0.9675,  0.0134, -1.4088],
        [-1.5676, -0.4853, -0.8766],
        [-0.3781,  0.1249,  0.4319]])
torch.Size([5, 3])
torch.Size([5, 3])


In [19]:
#加法
y = torch.rand(5,3)
print(x+y)
print(x.add(y)) #如果需要执行x=x+y 这种替换操作使用x.add_(y)
result = torch.empty(5,3)
torch.add(x,y,out = result)
print(result)

tensor([[ 0.2906,  0.1496,  2.2279],
        [ 1.3803,  0.6473,  2.4782],
        [ 0.9698,  0.9211, -1.0006],
        [-1.4828,  0.4075, -0.1841],
        [-0.1305,  0.2608,  0.7563]])
tensor([[ 0.2906,  0.1496,  2.2279],
        [ 1.3803,  0.6473,  2.4782],
        [ 0.9698,  0.9211, -1.0006],
        [-1.4828,  0.4075, -0.1841],
        [-0.1305,  0.2608,  0.7563]])
tensor([[ 0.2906,  0.1496,  2.2279],
        [ 1.3803,  0.6473,  2.4782],
        [ 0.9698,  0.9211, -1.0006],
        [-1.4828,  0.4075, -0.1841],
        [-0.1305,  0.2608,  0.7563]])


In [20]:
#索引结果与源数据共享内存，一个改了另外一个也会变
print(x)
y = x[0,:]
y += 1
print(y)
print(x[0,:])



tensor([[-0.3776,  0.0080,  1.3954],
        [ 0.5815, -0.2561,  2.3722],
        [ 0.9675,  0.0134, -1.4088],
        [-1.5676, -0.4853, -0.8766],
        [-0.3781,  0.1249,  0.4319]])
tensor([0.6224, 1.0080, 2.3954])
tensor([0.6224, 1.0080, 2.3954])


In [22]:
#view
y = x.view(-1,5)#设定-1表示该位会随着其他设置自行调整
print(y.shape)
#view也是共享数据，其中一个修改另一个也会改变
print(x)
y -= 1
print(y)
print(x)


torch.Size([3, 5])
tensor([[ 0.6224,  1.0080,  2.3954],
        [ 0.5815, -0.2561,  2.3722],
        [ 0.9675,  0.0134, -1.4088],
        [-1.5676, -0.4853, -0.8766],
        [-0.3781,  0.1249,  0.4319]])
tensor([[-0.3776,  0.0080,  1.3954, -0.4185, -1.2561],
        [ 1.3722, -0.0325, -0.9866, -2.4088, -2.5676],
        [-1.4853, -1.8766, -1.3781, -0.8751, -0.5681]])
tensor([[-0.3776,  0.0080,  1.3954],
        [-0.4185, -1.2561,  1.3722],
        [-0.0325, -0.9866, -2.4088],
        [-2.5676, -1.4853, -1.8766],
        [-1.3781, -0.8751, -0.5681]])


In [24]:
#如果想不共享内存推荐使用clone,clone可以记录在计算图里，梯度回传到副本也会回传到源
x_cp = x.clone().view(-1,3)
x -= 1
print(x)
print(x_cp)
#item 将标量tensor转化为Python number
x = torch.rand(1)
print(x)
print(x.item())
#pytorch支持超过一百种矩阵操作

tensor([[-2.3776, -1.9920, -0.6046],
        [-2.4185, -3.2561, -0.6278],
        [-2.0325, -2.9866, -4.4088],
        [-4.5676, -3.4853, -3.8766],
        [-3.3781, -2.8751, -2.5681]])
tensor([[-1.3776, -0.9920,  0.3954],
        [-1.4185, -2.2561,  0.3722],
        [-1.0325, -1.9866, -3.4088],
        [-3.5676, -2.4853, -2.8766],
        [-2.3781, -1.8751, -1.5681]])
tensor([0.6170])
0.6169828176498413


In [26]:
#广播机制，不同size的tensor通过复制元素完成运算
x = torch.arange(1,3).view(1,2)
y = torch.arange(1,4).view(3,1)
print(x)
print(y)
print(x+y)#x把第一行复制三行，y把第一列复制两列 对应相加

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


In [28]:
#y = x+y是会开辟新的内存的，然后将y指向新内存
x = torch.tensor([1,2])
y = torch.tensor([3,4])
id_before = id(y)
y[:] = x+y # 结果通过[:]写进y对应的内存中
print(id_before == id(y))
#同样的节约内存操作还有：
torch.add(x,y,out = y)
x.add_(y)


True


In [35]:
#tensor numpy互换
a = torch.ones([1,5])
b = a.numpy() #tensor->numpy,共享相同内存，一个变化另一个也会变化
print(a,b)
a += 1 
print(a,b)

c = torch.from_numpy(b) #numpy->tensor
print(b,c)
b += 1
print(b,c)

tensor([[1., 1., 1., 1., 1.]]) [[1. 1. 1. 1. 1.]]
tensor([[2., 2., 2., 2., 2.]]) [[2. 2. 2. 2. 2.]]
[[2. 2. 2. 2. 2.]] tensor([[2., 2., 2., 2., 2.]])
[[3. 3. 3. 3. 3.]] tensor([[3., 3., 3., 3., 3.]])


In [36]:
c = torch.tensor(a)
a+=1
print(c,a)

tensor([[3., 3., 3., 3., 3.]]) tensor([[4., 4., 4., 4., 4.]])


<ipython-input-36-fc8bc2dd8f72>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  c = torch.tensor(a)


In [39]:
#tensor on GPU
if torch.cuda.is_available():
    print(x)
    device = torch.device("cuda")
    cudax = torch.ones_like(x,device = device) #直接创建一个GPU说的Tensor
    x = x.to(device)#把x移到cuda
    z = x+cudax
    print(z)
    print(z.to("cpu",torch.double)) #to还能改数据类型

tensor([1, 2])
tensor([2, 3], device='cuda:0')
tensor([2., 3.], dtype=torch.float64)


In [42]:
#自动求梯度
x = torch.ones(2,2,requires_grad=True)#requires_grad默认False，可以通过x.requires_grad(True)设置
print(x)
print(x.grad_fn) #x不是通过运算得到的所以返回None
y = x+2
print(y)
print(y.grad_fn)#y是通过运算得到的所以返回相关对象
z = y*y*3
out = z.mean()
print(z,out)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [43]:
out.backward()#out是标量所以不需要传值进backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [45]:
#梯度是累加的所以再进行反向传播时记得梯度清零
x.grad.data.zero_()
#不允许张量对张量求导只能标量对张量求导
x = torch.tensor([1.0,2.0,3.0,4.0],requires_grad=True)
y = 2 * x
z = y.view([2,2])
print(z)
v = torch.tensor([[1.0,0.1],[0.01,0.001]],dtype=torch.float) #要传入一个和z同形的权重向量进行加权求和
z.backward(v) #相当于先计算l = torch.sum(y * v)
print(x.grad)

tensor([[2., 4.],
        [6., 8.]], grad_fn=<ViewBackward>)
tensor([2.0000, 0.2000, 0.0200, 0.0020])


In [46]:
#中断梯度追踪
x = torch.tensor(1.0,requires_grad=True)
y1 = x**2
with torch.no_grad():
    y2 = x**3
y3 = y1 + y2
y3.backward()
print(x.grad)
#因为y2中断梯度所以y2,requires_grad=False

tensor(2.)


In [47]:
#如果我们想要修改tensor的数值，但是又不希望被autograd记录（即不会影响反向传播），那么我么可以对tensor.data进行操作。
x = torch.ones(1,requires_grad=True)

print(x.data) # 还是一个tensor
print(x.data.requires_grad) # 但是已经是独立于计算图之外

y = 2 * x
x.data *= 100 # 只改变了值，不会记录在计算图，所以不会影响梯度传播

y.backward()
print(x) # 更改data的值也会影响tensor的值
print(x.grad)

tensor([1.])
False
tensor([100.], requires_grad=True)
tensor([2.])
